export { Menu } from './Menu'
export { Modal } from './Modal'

export { default as Range } from './Range'
export { default as Title } from './Title'
export { default as Button } from './Button'
export { default as Slide } from './Slide'
export { default as Footer } from './Footer'
export { default as Contato } from './Contato'
export { default as LiveChat } from './LiveChat'
